# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PockeTalk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Starscream', '~> 4.0.0'

  pod 'SQLite.swift', '~> 0.13.0'

  pod "SwiftyXMLParser", :git => 'https://github.com/yahoojapan/SwiftyXMLParser.git'
  
  pod 'TOCropViewController'
  
  pod 'Differ'
  
  pod 'SwiftRichString'

  # Pods for PockeTalk

  target 'PockeTalkTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
