# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PockeTalk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod "SwiftyXMLParser", :git => 'https://github.com/yahoojapan/SwiftyXMLParser.git'
  
  pod 'TOCropViewController'

  # Pods for PockeTalk

  target 'PockeTalkTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
